// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGxzlg81VZhyDFJK4CrRXSDl8VQSIatc',
    appId: '1:561533394446:web:8b4704aadfd46dc73c265f',
    messagingSenderId: '561533394446',
    projectId: 'todo-app-341d0',
    authDomain: 'todo-app-341d0.firebaseapp.com',
    storageBucket: 'todo-app-341d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfVS0IxKPernwN79rbmQaDjdZjyux3p_A',
    appId: '1:561533394446:android:9e23ebf040c874373c265f',
    messagingSenderId: '561533394446',
    projectId: 'todo-app-341d0',
    storageBucket: 'todo-app-341d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmQx8ODtI9GYvFtKwE8lTQFEqmPH6vgYI',
    appId: '1:561533394446:ios:3a13c8b4ea2f80eb3c265f',
    messagingSenderId: '561533394446',
    projectId: 'todo-app-341d0',
    storageBucket: 'todo-app-341d0.appspot.com',
    iosClientId: '561533394446-tskkvi97frus3ua1rfd9c64ghutsnarr.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmQx8ODtI9GYvFtKwE8lTQFEqmPH6vgYI',
    appId: '1:561533394446:ios:a10c3c6763bbe4fd3c265f',
    messagingSenderId: '561533394446',
    projectId: 'todo-app-341d0',
    storageBucket: 'todo-app-341d0.appspot.com',
    iosClientId: '561533394446-ijtvphqli29d8ets6l7dg4v9o4viso4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
